apiVersion: v2
name: auth-service
description: "Auth service for my portfolio project"
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: postgresql
    version: 18.2.0
    repository: https://charts.bitnami.com/bitnami
